USE sucos;

ALTER TABLE TABELA_DE_VENDEDORES ADD PRIMARY KEY (MATRICULA);

ALTER TABLE TABELA_DE_VENDEDORES ADD COLUMN (DATA_ADMISSÃO DATE);
ALTER TABLE TABELA_DE_VENDEDORES ADD COLUMN (DE_FERIAS BIT(1));