INSERT INTO TABELA_DE_VENDEDORES(
MATRICULA, NOME, PERCENTUAL_COMISSAO
)VALUES(
'00235', 'Márcio Almeida Silva', 8
);

INSERT INTO TABELA_DE_VENDEDORES(
MATRICULA, NOME, PERCENTUAL_COMISSAO
)VALUES(
'00236', 'Cláudia Morais', 8
);

